services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: commerce
    container_name: commerce-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - commerce

#   db:
#     image: mysql:9.2.0
#     container_name: commerce-db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_USER: ${DB_USERNAME}
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     volumes:
#       - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#     networks:
#       - commerce

#   nginx:
#     image: nginx:alpine
#     container_name: commerce-nginx
#     restart: unless-stopped
#     ports:
#       - "8000:80"
#     volumes:
#       - ./:/var/www
#       - ./docker-compose/nginx:/etc/nginx/conf.d
#     networks:
#       - commerce

networks:
  commerce:
    driver: bridge